# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

variables:
  AZURE_TEST_TYPE: "python"
  AZURE_SERVICE: "wellbore-domain-services-worker"
  AZURE_DEPLOYMENTS_SUBDIR: devops/azure
  AZURE_CLIENT_ID: $AZURE_PRINCIPAL_ID
  AZURE_CLIENT_SECRET: $AZURE_PRINCIPAL_SECRET
  AZURE_DATA_PARTITION: opendes
  AZURE_AD_APP_RESOURCE_ID: $AZURE_APP_ID
  KEYVAULT_URI: $KEYVAULT_URI
  AZURE_APP_CLIENT_SECRET: $AZURE_APP_CLIENT_SECRET
  STORAGE_ACCOUNT_NAME: $STORAGE_ACCOUNT_NAME
  AZURE_SKIP_TEST: "true"

  AWS_BUILD_SUBDIR: provider/os-wellbore-ddms-worker-aws/build-aws
  AWS_EKS_DEPLOYMENT_NAME: os-wellbore-ddms-worker
  AWS_SERVICE_NAMESPACE_SUFFIX: wellbore-ddms
  AWS_SERVICE: wellbore-ddms-worker
  AWS_DEPLOY_TARGET: TF

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
  - local: "/devops/azure/override-stages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"
  - local: "devops/gc/pipeline/override-stages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/core-global.yml"
  - local: "devops/core-plus/pipeline/override-stages.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-wellbore-bulk-worker.yml"

aws-containerize:
  needs: []

default:
  image: python:3.10-slim-bullseye
  before_script:
    - export PIP_EXTRA_INDEX_URL="https://community.opengroup.org/api/v4/projects/465/packages/pypi/simple https://community.opengroup.org/api/v4/projects/148/packages/pypi/simple"
    - pip3 install -e ".[dev]"
    - pip3 install -e ".[aws]"

stages:
  - linting
  - testing
  - review
  - build
  - coverage
  - containerize
  - scan
  - deploy
  - bootstrap
  - integration
  - acceptance
  - performance-testing
  - publish
  - deploy_preship

linters-check:
  tags: ["osdu-small"]
  stage: linting
  script:
    - black . --check
    - flake8 ./src
    - mypy ./src

unit-tests:
  tags: ["osdu-medium"]
  stage: testing
  script:
    - coverage run -m pytest ./tests/unit --junitxml=report.xml
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

service-tests:
  tags: ["osdu-medium"]
  stage: testing
  script:
    - coverage run -m pytest ./tests/service --junitxml=report.xml
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

trigger-trusted-tests:
  image: $CI_REGISTRY/osdu/platform/trusted-mr-container
  before_script:
    - echo "overriding before script"

trusted-merge-branch-verification:
  image: $CI_REGISTRY/osdu/platform/trusted-mr-container
  before_script:
    - echo "overriding before script"
