[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wdmsworker"
authors = [{name = "WDMS team"}]
description = "A python (3.10) WDMS bulk worker service."
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["python", "wdms", "bulk"]
requires-python = "~=3.10"
version = "0.1.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "pandas~=1.5.2",
    "pyarrow~=10.0.1",
    "natsort",
    "fastapi~=0.95.2",
    "uvicorn",
    "opencensus",
    "requests>=2.31.0",
    "osdu-core-lib-python==3.0.0",
]

[project.urls]
Home = "https://community.opengroup.org/osdu/platform/domain-data-mgmt-services/wellbore/wellbore-domain-services-worker"

[project.optional-dependencies]
test = [
    "anyio",
    "pytest",
    "pytest-cov",
    "pytest-randomly",
    "requests",  # based http client for the service tests
    "httpx",  # used by FastAPI/starlette TestClient
    "fsspec",  # local blob storage
]
dev = [
    "wdmsworker[test]",  # dependencies for tests
    "black",  # formatting
    "mypy",  # typing check
    "flake8",
    "Flake8-pyproject",
    "pre-commit", # for adding git pre-commit hook to run flake8, mypy and black automatically
]

pkg = [
    "setuptools",
    "wheel",
    "build"
]

# cloud provider specific dependencies
az = [
    "opencensus-ext-azure",
    "osdu-core-lib-python-azure==3.0.3",
    "opencensus-ext-logging",
]

aws = [
    "boto3==1.24.59",
    "botocore==1.27.59",
    "osdu-core-lib-python-aws==2.0.8",
]

ibm = [
    # TODO: add dependencies specific to ibm
]

gc = [
    # TODO: add dependencies specific to gc
]

anthos = [
    # TODO: add dependencies specific to anthos
]

[tool.pytest.ini_options]
pythonpath = ["."]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "perf: performance test, usually slow test"
]
#addopts = "--p no:randomly"  # uncomment to disable random order testing

[tool.mypy]
ignore_missing_imports = "True"

[tool.black]
line-length = 120
target-version = ['py310']
# Preview allows to split long strings
preview = true
exclude = '''
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv.*      # exclude all .venv
    | venv.*        # exclude all venv
    | \.idea
    | \.pytest_cache
    | \.hypothesis
    | \.vscode
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.flake8]
ignore = [
    'E203',  # See https://github.com/PyCQA/pycodestyle/issues/373
    'W503',  # W504 preferred
    'E501',  # 120 chars instead of 79
]
per-file-ignores = [
    '__init__.py:F401',  # disable unsued import file in __init__.py
]
max-line-length = 120
