global:
  domain: ""
  limitsEnabled: true
  tier: ""
  autoscaling: true

data:
  # Configmaps
  openapiPrefix: "/api/wdms-worker"
  # Deployments
  requestsCpu: "5m"
  requestsMemory: "350Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  gcImage: "community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/wellbore/wellbore-domain-services-worker/gc-wellbore-worker-master:latest"
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "wellbore-worker"

conf:
  configmap: "wellbore-worker-config"
  appName: "wellbore-worker"
  minioSecretName: "wellbore-minio-secret"
  replicas: 2

hpa:
  minReplicas: 6
  maxReplicas: 15
  targetType: "AverageValue"
  targetValue: 86 # 50*0.86*2
  behaviorScaleUpStabilizationWindowSeconds: 10
  behaviorScaleUpPoliciesValue: 50
  behaviorScaleUpPoliciesPeriodSeconds: 15
  behaviorScaleDownStabilizationWindowSeconds: 60
  behaviorScaleDownPoliciesValue: 25
  behaviorScaleDownPoliciesPeriodSeconds: 60

limits:
  maxTokens: 50
  tokensPerFill: 50
  fillInterval: "1s"
