# Copyright 2023 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from enum import Enum
from dataclasses import dataclass
from typing import List, Dict, Any, Iterable, Tuple, KeysView, Optional
from io import BytesIO
import json
from re import compile

import pandas as pd

from .errors import BulkValidationError
from .storage_path_builder import basename, hash_for_filename, split_path, join, relpath
from ..model.mime_types import MimeTypes

index_reg = r"[+-]?\d+(\.\d*)?"  # it can be an integer or a float
CHUNK_FILENAME_REGEX = compile(rf"^{index_reg}_{index_reg}_\d+(\.).+$")
CHUNK_FILENAME_REGEX_V2 = compile(r"^(\w){12}(\.)(\w){12}(\.).+$")


class ChunkMeta:
    """
    Gather extended information about chunks. Attributes:
        - filename: str, filename expected to be generated by this class using `generate_filename`
        - columns: list of column labels in the chunk. Order is preserved.
        - columns_hash: str, hash of the column, hash is invariant with the column order
        - index: index value at first, last row
        - index_hash: str, hash of the index given the start, end values and the length
        - nb_rows: int, number of rows
        - dtypes: List[str], dtype of each column
        - order: used to merge order in case of conflict resolution
        - conflict_group_id: id used to group several conflicting chunks
        - reference: reference value at first, last row
    """

    file_version = 2

    class FileType(int, Enum):
        META = 0  # this meta file
        CHUNK = 1  # parquet chunk file
        INDEX = 2  # index chunk file

    class Origin(int, Enum):
        DATAFRAME = 0  # constructed from a dataframe
        META_V1 = 1  # translated from meta file version 1
        META_V2 = 2  # loaded from meta file version 2

    @dataclass
    class ColumnStartEndValues:
        name: str
        start: Any
        end: Any
        dtype: str

        def ordered_range(self) -> Tuple[Any, Any]:
            if self.end > self.start:
                return self.start, self.end
            return self.end, self.start

        def is_increasing(self) -> bool:
            return self.end >= self.start

    def __init__(
        self,
        filepath: str,
        columns: Iterable[str],
        columns_hash: str,
        index_start_end: ColumnStartEndValues,
        index_hash: str,
        nb_rows: int,
        dtypes: Iterable[str],
        *,
        reference: ColumnStartEndValues | None = None,
        origin: Origin = Origin.META_V2,
    ):
        """
        :param filepath: str, filename expected to be generated by this class using `generate_filename`
        :param columns: list of column labels in the chunk. Order is preserved.
        :param columns_hash: str, hash of the column, hash is invariant with the column order
        :param index_start_end: start and end for the index
        :param index_hash: str, hash of the index given the start, end values and the length
        :param nb_rows: int, number of rows
        :param dtypes: column dtypes, if only one dtype means same dtypes for all columns
        :param reference: start and end for the reference values
        :param origin:
        """

        filename = self._filename_without_extension(filepath)
        self.index_hash = index_hash
        self.column_hash = columns_hash
        self._base_path, _ = split_path(filepath)
        self._filename = filename
        self._columns = list(columns)
        self._dtypes = list(dtypes)
        # in case dtype of columns are the same, a single value can be provided, then we expand it here
        if len(self._dtypes) == 1 and len(self._columns) > 1:
            common_type = self._dtypes[0]
            self._columns_set = {c: common_type for c in self._columns}
        else:
            self._columns_set = dict(zip(self._columns, self._dtypes))
        self._index = index_start_end
        self._ordered_range = index_start_end.ordered_range()
        self.nb_rows = nb_rows
        self.origin = origin
        self.order = 0
        self.conflict_group_id: int | None = None
        self._reference = reference

    @property
    def has_reference(self) -> bool:
        return self._reference is not None and bool(self._reference.name)

    @property
    def reference_name(self) -> str | None:
        return None if self._reference is None else self._reference.name

    @property
    def index(self) -> ColumnStartEndValues:
        return self._index

    @property
    def filename(self):
        return self._filename

    @property
    def base_path(self):
        return self._base_path

    @property
    def in_conflict(self) -> bool:
        return self.conflict_group_id is not None

    @property
    def is_index_increasing(self) -> bool:
        return self._index.is_increasing()

    def _relative_base_path(self, relative_to: str | None) -> str:
        return relpath(self._base_path, relative_to) if relative_to else self._base_path

    def get_filename(self, file_type: FileType) -> str:
        if file_type == self.FileType.CHUNK:
            return MimeTypes.PARQUET.add_extension(self._filename)
        if file_type == self.FileType.META:
            return MimeTypes.META.add_extension(self._filename)
        if file_type == self.FileType.INDEX:
            return MimeTypes.PARQUET.add_extension(f"index.{self.index_hash}")
        raise ValueError("unknown file type")

    def get_filepath(self, file_type: FileType, relative_to: str | None = None) -> str:
        """
        build file path of
        :param file_type:
        :param relative_to:
        :return:
        """
        base_path = self._relative_base_path(relative_to)
        return MimeTypes.PARQUET.add_extension(join(base_path, self.get_filename(file_type)))

    @staticmethod
    def is_a_chunk_file(filepath) -> bool:
        #  the purpose is to distinguish multi part/file chunk resulting of a chunk conflict resolution
        #  and saved by Dask. It might be more efficient in main cases (no conflict) to do this only if load of chunk
        #  failed (speed favors no conflict case). Eventually with the removal of Dask and chunk massaging, these
        #  cases will become rarer.
        filename = basename(filepath)
        return CHUNK_FILENAME_REGEX_V2.match(filename) is not None or CHUNK_FILENAME_REGEX.match(filename) is not None

    @classmethod
    def _get_shape_hash(cls, dataframe: pd.DataFrame) -> Tuple[str, str]:
        dtype, first_idx, last_idx = cls._edges_scalar(pd.Series(dataframe.index))
        shape_h = hash_for_filename((dtype, sorted(dataframe.columns.tolist())), size=12)
        index_h = hash_for_filename((first_idx, last_idx, len(dataframe)), size=12)
        return index_h, shape_h

    @classmethod
    def _filename_from_hashes(cls, index_hash: str, column_shape: str) -> str:
        return f"{index_hash}.{column_shape}"

    @classmethod
    def generate_filename(cls, dataframe: pd.DataFrame) -> str:
        """construct a filename without extension this way: {index_hash}.{column_hash}:
           - index_hash takes into account the first and last index value and its length
           - column_hash takes into_account all column labels with types and index type
           This method is idempotent and same shape dataframe produce same filename, column order doesn't matter
           if two chunk produce the same filename, it means two chunks with same shape were pushed within same session,
           therefore last come wins policy is applied.
        :param dataframe: dataframe
        :raise: IndexError - if empty dataframe
        :return: filename as string
        """
        index_h, shape_h = cls._get_shape_hash(dataframe)
        return cls._filename_from_hashes(index_h, shape_h)

    def start_end_df(self) -> pd.DataFrame:
        """constructs and returns a dataframe from start end index values including reference if set"""
        index_values = [self._index.start, self._index.end] if self.nb_rows > 1 else [self._index.start]
        if self._reference is not None:
            ref_values = [self._reference.start, self._reference.end] if self.nb_rows > 1 else [self._reference.start]
            df = pd.DataFrame({self._reference.name: ref_values}, index=index_values)
            df[self._reference.name].astype(self._reference.dtype, copy=False)
            return df

        return pd.DataFrame(index=index_values)

    @property
    def columns(self) -> List[str]:
        return self._columns

    @property
    def columns_set(self) -> KeysView[str]:
        return self._columns_set.keys()

    @property
    def column_dtypes(self) -> Dict[str, str]:
        return self._columns_set

    def columns_contains(self, label: str) -> bool:
        return label in self._columns_set

    def share_columns_with(self, other: "ChunkMeta") -> bool:
        """
        check if current chunk shared at least one column with the other one
        :param other:
        :return: `True` if any column in common, `False` otherwise
        """
        return not self.columns_set.isdisjoint(other._columns)

    def index_overlap_with(self, other: "ChunkMeta") -> bool:
        """
        check if there's any index overlap regardless the columns
        :param other:
        :return: `True` if index overlap, `False` otherwise
        """
        r1 = self._ordered_range
        r2 = other._ordered_range
        return not (r2[0] > r1[1] or r2[1] < r1[0])

    def overlap_with(self, other: "ChunkMeta") -> bool:
        """
        check if there's overlap of both columns and index
        :param other:
        :return: `True` if overlap, `False` otherwise
        """
        return self.share_columns_with(other) and self.index_overlap_with(other)

    @property
    def filename_with_extension(self) -> str:
        return MimeTypes.META.add_extension(self._filename)

    @classmethod
    def _filename_without_extension(cls, filepath: str) -> str:
        filename = basename(filepath)
        if MimeTypes.META.match_extension(filename):
            return filename.replace("." + MimeTypes.META.extension, "")
        return filename

    @classmethod
    def _reduce_dtypes(cls, dtypes: List[str]) -> List[str]:
        """
        reduce list of dtype to a single value list if, and only if all dtypes are the same
        """
        if dtypes.count(dtypes[0]) == len(dtypes):
            return [dtypes[0]]
        return dtypes

    @classmethod
    def _edges_scalar(cls, series: pd.Series) -> Tuple[str, int, int] | Tuple[str, float, float]:
        """
        normalize an index first, lst values into python int or float
        :param : index series
        :return: dtype in string followed by int or float first, last values
        """
        if series.empty:
            raise ValueError("Series cannot be empty")
        dtype = str(series.dtype)
        start, end = series.iloc[0], series.iloc[-1]
        if "float" in dtype:
            return dtype, float(start), float(end)
        if "int" in dtype:
            return dtype, int(start), int(end)
        if "time" in dtype:
            # this will provide date time as integer usually with nanosecond precision
            return dtype, int(start.value), int(end.value)
        raise ValueError("unsupported index type")

    @classmethod
    def _try_load_as_previous_format(cls, filepath: str, meta_dict: Dict) -> Optional["ChunkMeta"]:
        """
        check if chunk meta is using previous format, if not return `None`. Otherwise creates and returns an instance of
        ChunkMeta translating previous format into current format
        :param filepath: file path from which meta dict is loaded
        :param meta_dict: meta content dict
        :return: None if not previous format else ChunkMeta instance
        """
        file_name = basename(filepath)
        if "file_version" in meta_dict or not CHUNK_FILENAME_REGEX.match(file_name):
            return None  # not a previous version

        # algo from wdms session_file_meta.py
        start, end, tail = file_name.split("_")
        column_hash = tail.split(".")[1]

        # previous file_version, translate it
        try:
            index_start: int | float = int(start)
            index_end: int | float = int(end)
            index_dtype = "int"
        except ValueError:
            index_start, index_end = float(start), float(end)
            index_dtype = "float"

        index_hash = meta_dict["index_hash"]

        return cls(
            filepath,
            meta_dict["columns"],
            column_hash,
            cls.ColumnStartEndValues("", index_start, index_end, index_dtype),
            index_hash,
            meta_dict["nb_rows"],
            cls._reduce_dtypes(meta_dict["dtypes"]),
            origin=cls.Origin.META_V1,
        )

    @classmethod
    def load(cls, filepath: str, content: bytes) -> "ChunkMeta":
        """
        :param filepath: origin filepath of given chunk meta content
        :param content:
        :return: ChunkMeta instance
        """
        meta_dict = json.load(BytesIO(content))
        meta_previous_format = cls._try_load_as_previous_format(filepath, meta_dict)
        if meta_previous_format is not None:
            return meta_previous_format

        if "reference" in meta_dict:
            reference = cls.ColumnStartEndValues(
                meta_dict["reference"],
                meta_dict["reference_start"],
                meta_dict["reference_end"],
                meta_dict["reference_dtype"],
            )
        else:
            reference = None

        return cls(
            filepath,
            meta_dict["columns"],
            meta_dict["column_hash"],
            cls.ColumnStartEndValues("", meta_dict["index_start"], meta_dict["index_end"], meta_dict["index_dtype"]),
            meta_dict["index_hash"],
            meta_dict["nb_rows"],
            meta_dict["dtypes"],
            reference=reference,
        )

    @classmethod
    def from_dataframe(
        cls,
        df: pd.DataFrame,
        base_folder: str | None = None,
        filename: str | None = None,
        reference_curve: str | None = None,
    ) -> "ChunkMeta":
        """
        build chunk meta from a dataframe. It will generate filename but base path will be empty
        :param df:
        :param base_folder:
        :param filename:
        :param reference_curve: name of reference curve if any
        :return:
        """
        if df.empty:
            raise ValueError("dataframe cannot be empty")

        index_hash, column_hash = cls._get_shape_hash(df)
        filename = filename or cls._filename_from_hashes(index_hash, column_hash)

        if base_folder:
            filepath = join(base_folder, filename)
        else:
            filepath = filename

        index_dtype, first, last = cls._edges_scalar(pd.Series(df.index))
        if reference_curve and reference_curve in df:
            reference_series = df[reference_curve]
            ref_dtype, ref_start, ref_end = cls._edges_scalar(reference_series)
            reference = cls.ColumnStartEndValues(reference_curve, ref_start, ref_end, ref_dtype)
        else:
            reference = None

        return cls(
            filepath,
            df.columns.to_list(),
            column_hash,
            cls.ColumnStartEndValues("", first, last, index_dtype),
            index_hash,
            len(df),
            cls._reduce_dtypes([str(dt) for dt in df.dtypes]),
            origin=cls.Origin.DATAFRAME,
            reference=reference,
        )

    def dump(self) -> bytes:
        """
        serialized as json format
        :return: bytes
        """
        meta_dict = {
            "file_version": self.file_version,
            "columns": self.columns,
            "index_dtype": self._index.dtype,
            "index_start": self._index.start,
            "index_end": self._index.end,
            "nb_rows": self.nb_rows,
            "index_hash": self.index_hash,
            "column_hash": self.column_hash,
            "dtypes": self._dtypes,
        }

        if self._reference is not None:
            meta_dict["reference"] = self._reference.name
            meta_dict["reference_start"] = self._reference.start
            meta_dict["reference_end"] = self._reference.end
            meta_dict["reference_dtype"] = self._reference.dtype

        return json.dumps(meta_dict).encode()


def sort_chunk_metas_by_index(chunk_metas: List[ChunkMeta]) -> List[ChunkMeta]:
    """
    sort list of chunk meta based on index. All must be either increasing or decreasing, raise BulkValidation error
    otherwise.
    :param chunk_metas:
    :return:
    """
    if not chunk_metas:
        return []

    # validate and determine if all increasing or all decreasing
    orders = set(m.is_index_increasing for m in chunk_metas if m.nb_rows > 1)
    if len(orders) > 1:
        raise BulkValidationError("chunk indexes must be all increasing or all decreasing")

    is_increasing = orders.pop() if orders else True  # if all chunks have only 1 row, increasing by convention
    sorted_chunks = sorted(chunk_metas, key=lambda m: m.index.start)
    if is_increasing:
        return sorted_chunks

    return list(reversed(sorted_chunks))
