{{- template "common.serviceaccount" (list . "os-wellbore-ddms-worker.serviceaccount") -}}
{{- define "os-wellbore-ddms-worker.serviceaccount" -}}
## Define overrides for the service's service account resource here
{{- end -}}