variables:
  CORE_SERVICE: wellbore-worker
  CORE_INT_TEST_TYPE: python
  CORE_SUPPORTED_PLATFORM: "linux/amd64"


core-containerize-gitlab:
  needs: []
  variables:
    CORE_BUILD_PATH: "./devops/core-plus/Dockerfile"

core-containerize-bootstrap-gitlab:
  needs: []

core-deploy:
  before_script:
    - echo "Deploying a new App version..."

core-test-python:
  rules:
    - exists:
        - never/existing/file.txt
