apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  CLOUD_PROVIDER: {{ .Values.data.cloudProvider | quote }}
  SERVICE_NAME: {{ .Values.conf.appName | quote }}
  OPENAPI_PREFIX: {{ .Values.data.openapiPrefix | quote }}
