apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.conf.appName | quote }}
  replicas: {{ .Values.conf.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.conf.appName | quote }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: {{ .Values.conf.appName | quote }}
          image: {{ .Values.data.image | quote }}
          imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
          envFrom:
          - configMapRef:
              name: {{ printf "%s-config" .Values.conf.appName | quote }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.data.requestsCpu | quote }}
              memory: {{ .Values.data.requestsMemory | quote }}
            {{- if .Values.global.limitsEnabled }}
            limits:
              cpu: {{ .Values.data.limitsCpu | quote }}
              memory: {{ .Values.data.limitsMemory | quote }}
            {{- end }}
      serviceAccountName: {{ .Values.data.serviceAccountName | quote }}
