# Copyright 2023 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{$nameSuffix := include "os-wellbore-ddms-worker.name-suffix" .}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "os-wellbore-ddms-worker.commonAnnotations" . | indent 4}}
  labels:
{{ include "os-wellbore-ddms-worker.commonLabels" . | indent 4}}
  name: {{ .Values.deployment.name }}{{ $nameSuffix }}
{{ include "os-wellbore-ddms-worker.namespace" . | indent 2}}
spec:
  {{- if not .Values.isAutoscalingEnabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
{{ include "os-wellbore-ddms-worker.commonLabels" . | indent 6}}
  template:
    metadata:
      annotations:
{{ include "os-wellbore-ddms-worker.commonAnnotations" . | indent 8}}
      labels:
        aadpodidbinding: "{{ .Values.labels.aadpodidbinding }}"
{{ include "os-wellbore-ddms-worker.commonLabels" . | indent 8}}
    spec:   
{{- if .Values.nodepool }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            {{- range $.Values.node_selector_labels }}
            - matchExpressions:
              - key: {{ . }}
                operator: In
                values:
                - {{ $.Values.nodepool }}
            {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - os-wellbore-ddms-worker{{ include "os-wellbore-ddms-worker.name-suffix" . }}
              topologyKey: topology.kubernetes.io/zone
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: os-wellbore-ddms-worker{{ include "os-wellbore-ddms-worker.name-suffix" . }}
{{- end }}   
      volumes:
        # Note:
        # This volume is required for pod-identity access mode (https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/pod-identity-mode.md)
        # Even if not directly used by the application, it is still required indirectly to allow the secretProviderClass to sync the secret, because the secret is only created as a side effect of workload mounting its content. 
        # 
        # Some more explanation:
        # https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/132#issuecomment-646349209
        # "It's not possible to only sync as a kubernetes secret and not have the contents mounted as files in the pod. The sync as K8s secret is done by getting the contents from the fs."
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault"
      containers:
      - name: {{ .Values.deployment.name }}      
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
          - containerPort: 8080
        # This preStop hook has been added as a temporary workaround to minimize downtime during deployments until this limitation is addressed at the AGIC level
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}{{ $nameSuffix }}
        env:
        - name: AZ_AI_CONNECTION_STR
          valueFrom:
            secretKeyRef:
              name: {{ .Values.deployment.instrumentationKey.secretName }}
              key: appinsights-connection-string
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: tenantid
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientid
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: active-directory
              key: principal-clientpassword
        - name: WORKSPACE_ID
          valueFrom:
            secretKeyRef:
              name: central-logging
              key: workspace-id
        - name: KEYVAULT_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.deployment.osduSvcProperties }}
              key: {{ .Values.deployment.keyvaultUrlPropertyName }}
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        volumeMounts:
          # This mount is not used by the application but is required for the secretProviderClass
          # See more comment on the Volume definition
          - mountPath: /azure-keyvault
            name: azure-keyvault
            readOnly: true
        resources:
          {{ toYaml .Values.resources | nindent 10 }}

      terminationGracePeriodSeconds: 45
