# Copyright 2023 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- define "originsRegex" }}^({{ range $index, $origin := . }}{{ if $index }}|{{ end }}{{ if contains "*" $origin }}{{ $origin | replace "*" "__WILDCARD__" | replace "." "\\." | replace "__WILDCARD__" ".*" }}{{ else }}{{ $origin | replace "." "\\." | replace "-" "\\-" }}{{ end }}{{ end }})${{ end }}
{{- if .Values.istioDnsHost }}
{{- $apiPrefix := include "os-wellbore-ddms-worker.prefix" . }}
{{- $origins := default (list) .Values.trustedOrigins }}
{{- $trustedOriginsRegExp := include "originsRegex" $origins }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
{{ include "os-wellbore-ddms-worker.commonAnnotations" . | indent 4}}
  labels:
{{ include "os-wellbore-ddms-worker.commonLabels" . | indent 4}}
  name: {{ .Values.deployment.name }}{{ include "os-wellbore-ddms-worker.name-suffix" . }}
{{ include "os-wellbore-ddms-worker.namespace" . | indent 2}}
spec:
  http:
{{- if gt (len $origins) 0 }}
  - match:
    - uri:
        prefix: '{{ $apiPrefix }}/'
      headers:
        origin:
          regex: '{{ $trustedOriginsRegExp }}'
    route:
    - destination:
        host: {{ .Values.deployment.name }}{{ include "os-wellbore-ddms-worker.name-suffix" . }}
        port:
          number: 80
    corsPolicy:
      maxAge: "60m"
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Data-Partition-Id
      - Correlation-Id
      - Content-Type
      allowMethods:
      - POST
      - GET
      allowOrigins:
{{- range $origins }}
{{- if contains "*" . }}
      - regex: '^{{ . | replace "*" "__WILDCARD__" | replace "." "\\." | replace "__WILDCARD__" ".*" }}$'
{{- else }}
      - exact: {{ . | quote }}
{{- end }}
{{- end }}
  - match:
    - uri:
        prefix: '{{ $apiPrefix }}/'
      headers:
        origin:
          regex: ".+"
      withoutHeaders:
        origin:
          regex: '{{ $trustedOriginsRegExp }}'
    directResponse:
      status: 403
      body:
        string: CORS origin not allowed
{{- end }}
  - match:
    - uri:
        prefix: '{{ $apiPrefix }}/'
    route:
    - destination:
        host: {{ .Values.deployment.name }}{{ include "os-wellbore-ddms-worker.name-suffix" . }}
        port:
          number: 80
    corsPolicy:
      maxAge: "60m"
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Data-Partition-Id
      - Correlation-Id
      - Content-Type
      allowMethods:
      - POST
      - GET
      allowOrigins:
          - prefix: "*"
{{- end }}