# Copyright © 2020 Amazon Web Services
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
[environment]
storage_url=notused
search_url=notused
legal_url=notused
data_workflow_url=notused
entitlements_url=%(SERVICE_HOST_ENTITLEMENTS)s/v2
file_dms_url=notused
dataset_url=notused
schema_url=notused
ingestion_workflow_url=notused
partition_url=%(PARTITION_HOST)s
use_service_principal=True

[provider]
name=aws
service_principal_module_name=service_principal_util
partition_info_converter_module=partition_converter_aws
token_url_ssm_path=token_url_ssm_path
aws_oauth_custom_scope_ssm_path=aws_oauth_custom_scope
client_id_ssm_path=client_id_ssm_path
client_secret_name=client_secret_name
client_secret_dict_key=client_credentials_client_secret
region_name=%(AWS_REGION)s
