# Copyright 2023 Schlumberger
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Template pipeline used to build and test the worker with different python versions

parameters:
- name: python_version
  type: string
  default: ''

steps:
# Use Python version
# Use the specified version of Python from the tool cache, optionally adding it to the PATH
- task: UsePythonVersion@0
  inputs:
    versionSpec: ${{ parameters.python_version }}
    addToPath: true
    architecture: 'x64'

- bash: |
    export PIP_EXTRA_INDEX_URL="https://community.opengroup.org/api/v4/projects/465/packages/pypi/simple https://community.opengroup.org/api/v4/projects/148/packages/pypi/simple"
    python -m venv venv
    source venv/bin/activate
    pip install -e ".[dev]"
  displayName: 'setup environment'

- bash: |
    source venv/bin/activate
    black . --check
  displayName: 'code format check - black'

- bash: |
    source venv/bin/activate
    flake8 ./src
  displayName: 'code checks & styling - flake8'

- bash: |
    source venv/bin/activate
    mypy ./src
  displayName: 'check static typing - mypy'